---
title: 'Analysis: Derived interactomes'
author: "Daniel Paysan"
date: "08/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/daniel/PycharmProjects/image2reg/")
```

# 0. Environmental setup

```{r environmental setup}
require("topGO")
require("KEGGREST")
require("org.Hs.eg.db")
require("GeneAnswers")
require("EnrichmentBrowser")
```

```{r}
# taken from https://github.com/karthikshekhar/CellTypeMIMB/blob/master/utilities.R
topGOterms = function(fg.genes = NULL,
                      bg.genes = NULL,
                      organism = "Mouse",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 100) {
  if (is.null(fg.genes) | is.null(bg.genes)) {
    stop("Error : Both gene lists are empty")
  }
  
  require(topGO)
  if (organism == "Mouse") {
    mapping.use = "org.Mm.eg.db"
    require(org.Mm.eg.db)
  } else if (organism == "Human") {
    mapping.use = "org.Hs.eg.db"
    require(org.Hs.eg.db)
  } else {
    stop("Error : Organisms other than mouse not supported currently")
  }
  
  n = length(bg.genes)
  geneList = integer(n)
  names(geneList) = bg.genes
  geneList[intersect(names(geneList), fg.genes)] = 1
  print(paste0(
    "Total ",
    length(geneList),
    " genes. ",
    sum(geneList),
    " genes in the foreground"
  ))
  geneList = factor(geneList)
  
  if (ontology.use %in% c("BP", "CC", "MF")) {
    print(paste0("Using Ontology : ", ontology.use))
  } else {
    stop("Error: Ontology not available. Should be one of BP, CC or MF")
  }
  # Make GO object
  GOdata <- new(
    "topGOdata",
    description = "GOanalysis",
    ontology = ontology.use,
    allGenes = geneList,
    annot = annFUN.org,
    mapping = mapping.use,
    ID = "SYMBOL",
    nodeSize = 10
  )
  print(paste0(
    "Using the ",
    stats.use,
    " statistic with the ",
    algorithm.use,
    " algorithm"
  ))
  res.result <-
    runTest(GOdata, statistic = stats.use, algorithm = algorithm.use)
  to.return = list()
  to.return$GOdata = GOdata
  
  allGO = usedGO(object = GOdata) 
  
  to.return$res.table <-
    GenTable(GOdata,
             pval = res.result,
             topNodes = length(allGO),
             numChar = num.char)
  return(to.return)
}
```

# 1. Read in data

We will now load in the gene sets describing the results of the PPI inference.

## 1a. Steiner tree solution
```{r steiner tree, echo=FALSE}
steiner_tree_selected_nodes <- read.csv("../../data/ppi/steiner_tree_selected_nodes.csv", row.names = 1)
```

```{r}
pcst_alpha_1_0_beta_1_k_0_selected_nodes <- read.csv("../../data/ppi/pcst_alpha_1_0_beta_1_k_0_selected_nodes.csv", row.names = 1)
```


# 2. Gene Ontology analyses of the gene sets

## 2a. Steiner tree solution

```{r}
selected_genes <- rownames(steiner_tree_selected_nodes)[steiner_tree_selected_nodes$type=="steiner"]
all_genes <- rownames(steiner_tree_selected_nodes)
```

```{r}
all_genes <- c('CDCA2', 'APPBP2', 'TK1', 'MMP2', 'PRKACA', 'CDC45', 'NOTCH3', 'SPARC', 'FBN1', 'FBLN1', 'RUNX1', 'SREBF1', 'STAC', 'TNNT1', 'GTSE1', 'TNNC1', 'YWHAQ', 'ERG', 'BIRC5', 'PRKCA', 'ACAN', 'CASP8', 'LZTS2', 'SPC25', 'MAPK7', 'S100A2', 'TUBB2B', 'CDC6', 'DHRS2', 'CEBPA', 'BEX1', 'UCHL5', 'HSPB1', 'WEE1', 'BMP4', 'PRAME', 'MYL2', 'SUV39H1', 'SDC2', 'TNC', 'DIABLO', 'DNMT3B', 'APC', 'TPM1', 'FKBP4', 'MAGEA6', 'LTBP2', 'CNN1', 'CLSPN', 'CRMP1', 'MCM4', 'GLI1', 'PKIA', 'CDKN1A', 'COL4A2', 'MAGEA1', 'MCM5', 'CDC42EP1', 'PCNA', 'JUN', 'NCF2', 'FOS', 'CD40', 'MAGED1', 'FBN2', 'MAP2K3', 'YES1', 'CDCA3', 'BCL2L11', 'AURKA', 'CCND2', 'MAP3K5', 'PRC1', 'TP73', 'CYBA', 'CDK14', 'TIMP1', 'TLR4', 'MAGEA4', 'PLCG1', 'CEP192', 'FOXM1', 'HRAS', 'KRT18', 'NCAPH', 'UBE2S', 'FN1', 'KPNA2', 'PTN', 'MYH9', 'HJURP', 'MAP3K9', 'LGALS1', 'FGFR2', 'CDC42', 'SMAD4', 'UBE2C', 'E2F1', 'BAX', 'CRYAB', 'PDGFRB', 'OIP5', 'VCAN', 'COL5A1', 'MDC1', 'CCNE1', 'ELK1', 'ZWINT', 'FOXO1', 'SRC', 'PCOLCE', 'FGF1', 'PIK3R2', 'AMPH', 'SMO', 'DUSP6', 'LDOC1', 'RPS6KB1', 'TRIB3', 'TRAF2', 'KRAS', 'BRAF', 'KRT81', 'TRIP6', 'SKP2', 'NCAM1', 'TUBB', 'EPB41L3', 'MYBL2', 'IRAK4', 'NEK2', 'COL4A1', 'CREB1', 'KIF15', 'KRT80', 'ATXN7', 'CDK1', 'AKT1S1', 'RARA', 'CKS2', 'HSP90AB1', 'TGFB1', 'PRKCE', 'MAPK8', 'EFEMP1', 'MKI67', 'PTCH1', 'RELB', 'NDN', 'KRT8', 'RHOA', 'AURKB', 'PAK2', 'GSK3B', 'CLU', 'HAPLN1', 'STC2', 'TPX2', 'KLK6', 'SPC24', 'MCM7', 'CCNB1', 'MAGEA11', 'WWTR1', 'MBP', 'ALOX5', 'FEN1', 'FSTL1', 'HSPG2', 'VIM', 'MYD88', 'CDK6', 'TUBA1A', 'GLI2', 'NDC80', 'ARMCX2', 'CDC20', 'SDC1', 'MDFI', 'EEF1A2', 'DSP', 'FGFR3', 'IGFBP5', 'THY1', 'PLK1', 'PARP2', 'TONSL', 'TCF4', 'CCNB2', 'CENPE', 'HSPA1B', 'MFAP2', 'SFN', 'MYC', 'BUB1B', 'KIF4A', 'CCNF', 'GABRB3', 'MAP3K2', 'LAMA1', 'BUB1', 'LOXL4', 'C1QL1', 'NUF2', 'AXL', 'AQP1', 'SDC3', 'S100A14', 'LBH', 'TGM2', 'KIF23', 'INHBA', 'SMAD3', 'BCR', 'TNNT2', 'THBS1', 'TSC2', 'NEFL', 'RAF1', 'KIF2C', 'MCM10', 'KRT15', 'RRM2', 'TENM3', 'FHL2', 'MCM3', 'NCOR2', 'GNAQ', 'THRA', 'MYL9', 'CCNA2', 'IRF7', 'MSH2', 'COL1A1', 'EXO1', 'GIT1', 'PCLO', 'IGF2', 'TPM2', 'ATF4', 'CENPA', 'PLCB2', 'CDK2', 'TUBB6')

selected_genes <- c('APC', 'AURKA', 'AURKB', 'BIRC5', 'BUB1', 'BUB1B', 'CCNA2', 'CCNB1', 'CCNB2', 'CCND2', 'CCNE1', 'CCNF', 'CDC20', 'CDC45', 'CDC6', 'CDCA2', 'CDCA3', 'CDK1', 'CDK2', 'CDK6', 'CDKN1A', 'CENPE', 'CEP192', 'CKS2', 'CLSPN', 'DIABLO', 'DNMT3B', 'E2F1', 'EXO1', 'FEN1', 'FOXM1', 'GTSE1', 'HSPA1B', 'KIF15', 'KIF23', 'KIF2C', 'KIF4A', 'MAPK7', 'MCM10', 'MCM3', 'MCM4', 'MCM5', 'MCM7', 'MKI67', 'MSH2', 'MYBL2', 'MYC', 'NCAPH', 'NDC80', 'NEK2', 'NUF2', 'PCNA', 'PLK1', 'PRC1', 'RRM2', 'SKP2', 'SPC24', 'SPC25', 'TNNC1', 'TONSL', 'TP73', 'TPX2', 'UBE2C', 'UBE2S', 'WEE1', 'ZWINT')
```


```{r}
steiner_go_results <-  topGOterms(fg.genes = selected_genes,
                      bg.genes = all_genes,
                      organism = "Human",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 70)
steiner_go_results$res.table[,"FDR"] <- p.adjust(steiner_go_results$res.table$pval, method="fdr")
head(steiner_go_results$res.table, 10)
```

## 2b. PC Steiner tree solution

```{r}
selected_genes <- rownames(pcst_alpha_1_0_beta_1_k_0_selected_nodes)[pcst_alpha_1_0_beta_1_k_0_selected_nodes$type=="steiner"]
all_genes <- rownames(pcst_alpha_1_0_beta_1_k_0_selected_nodes)
```

```{r}
pcst_go_results <-  topGOterms(fg.genes = selected_genes,
                      bg.genes = all_genes,
                      organism = "Human",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 100)
pcst_go_results$res.table[,"FDR"] <- p.adjust(pcst_go_results$res.table$pval, method="fdr")
head(pcst_go_results$res.table[,c("GO.ID", "Term", "FDR")], 10)
```

