---
title: 'Analysis: Derived interactomes'
author: "Daniel Paysan"
date: "08/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/home/daniel/PycharmProjects/image2reg/")
```

# 0. Environmental setup

```{r environmental setup}
require("topGO")
require("KEGGREST")
require("org.Hs.eg.db")
require("GeneAnswers")
require("EnrichmentBrowser")
```

```{r}
# taken from https://github.com/karthikshekhar/CellTypeMIMB/blob/master/utilities.R
topGOterms = function(fg.genes = NULL,
                      bg.genes = NULL,
                      organism = "Mouse",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 100) {
  if (is.null(fg.genes) | is.null(bg.genes)) {
    stop("Error : Both gene lists are empty")
  }
  
  require(topGO)
  if (organism == "Mouse") {
    mapping.use = "org.Mm.eg.db"
    require(org.Mm.eg.db)
  } else if (organism == "Human") {
    mapping.use = "org.Hs.eg.db"
    require(org.Hs.eg.db)
  } else {
    stop("Error : Organisms other than mouse not supported currently")
  }
  
  n = length(bg.genes)
  geneList = integer(n)
  names(geneList) = bg.genes
  geneList[intersect(names(geneList), fg.genes)] = 1
  print(paste0(
    "Total ",
    length(geneList),
    " genes. ",
    sum(geneList),
    " genes in the foreground"
  ))
  geneList = factor(geneList)
  
  if (ontology.use %in% c("BP", "CC", "MF")) {
    print(paste0("Using Ontology : ", ontology.use))
  } else {
    stop("Error: Ontology not available. Should be one of BP, CC or MF")
  }
  # Make GO object
  GOdata <- new(
    "topGOdata",
    description = "GOanalysis",
    ontology = ontology.use,
    allGenes = geneList,
    annot = annFUN.org,
    mapping = mapping.use,
    ID = "SYMBOL",
    nodeSize = 10
  )
  print(paste0(
    "Using the ",
    stats.use,
    " statistic with the ",
    algorithm.use,
    " algorithm"
  ))
  res.result <-
    runTest(GOdata, statistic = stats.use, algorithm = algorithm.use)
  to.return = list()
  to.return$GOdata = GOdata
  
  allGO = usedGO(object = GOdata) 
  
  to.return$res.table <-
    GenTable(GOdata,
             pval = res.result,
             topNodes = length(allGO),
             numChar = num.char)
  return(to.return)
}
```

# 1. Read in data

We will now load in the gene sets describing the results of the PPI inference.

## 1a. Steiner tree solution
```{r steiner tree, echo=FALSE}
steiner_tree_selected_nodes <- read.csv("../../data/ppi/steiner_tree_selected_nodes.csv", row.names = 1)
```

```{r}
pcst_alpha_1_0_beta_1_k_0_selected_nodes <- read.csv("../../data/ppi/pcst_alpha_1_0_beta_1_k_0_selected_nodes.csv", row.names = 1)
```


# 2. Gene Ontology analyses of the gene sets

## 2a. Steiner tree solution

```{r}
selected_genes <- rownames(steiner_tree_selected_nodes)[steiner_tree_selected_nodes$type=="steiner"]
all_genes <- rownames(steiner_tree_selected_nodes)
```

```{r}
steiner_go_results <-  topGOterms(fg.genes = selected_genes,
                      bg.genes = all_genes,
                      organism = "Human",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 100)
steiner_go_results$res.table[,"FDR"] <- p.adjust(steiner_go_results$res.table$pval, method="fdr")
head(steiner_go_results$res.table[,c("GO.ID", "Term", "FDR")], 10)
```

## 2b. PC Steiner tree solution

```{r}
selected_genes <- rownames(pcst_alpha_1_0_beta_1_k_0_selected_nodes)[pcst_alpha_1_0_beta_1_k_0_selected_nodes$type=="steiner"]
all_genes <- rownames(pcst_alpha_1_0_beta_1_k_0_selected_nodes)
```

```{r}
pcst_go_results <-  topGOterms(fg.genes = selected_genes,
                      bg.genes = all_genes,
                      organism = "Human",
                      ontology.use = "BP",
                      stats.use = "fisher",
                      algorithm.use = "weight01",
                      num.char = 100)
pcst_go_results$res.table[,"FDR"] <- p.adjust(pcst_go_results$res.table$pval, method="fdr")
head(pcst_go_results$res.table[,c("GO.ID", "Term", "FDR")], 10)
```

