output_dir: "/data/xinyi/image2reg/data_new/experiments/jump_compound/images/preprocessing/full_pipeline"
module: "src.preprocessing.image_preprocessing"
class: "ImageJUMPDatasetPreprocessor"

run_params:
  image_input_dir: "/data/xinyi/image2reg/data_new/resources/images/jump_compound/raw"
  illum_image_dir: "/data/xinyi/image2reg/data_new/resources/images/jump_compound/illum_corrected"
  metadata_file: "/data/xinyi/image2reg/data_new/resources/images/jump_compound/metadata/image_loc_metadata.csv.gz"
  illum_image_col_name: "IllumImageLoc"
  plate_col_name: "Metadata_Batch"
  well_col_name: "Metadata_Well"

pipeline:
  # - method: get_nuclear_crops
  #   params:
  #     label_image_input_dir: "/data/xinyi/image2reg/data_new/resources/images/jump_compound/unet_masks"
  #     nuclei_count_col_name: "Count_Cells"
  #     min_area: 400
  #     max_area: 4000
  #     max_bbarea: 4000
  #     max_eccentricity: 1.0
  #     min_solidity: 0.1
  #     min_aspect_ratio: 0.1
  #     n_jobs: 1
  #     extract_ncmo_features: False

  - method: save_padded_images
    params:
      nuclei_metadata_file: "/data/xinyi/image2reg/data_new/experiments/jump_compound/images/preprocessing/full_pipeline/20241025_161036/processed_nuclei_metadata.csv.gz"
      target_size: [64,64]
      input_dir: "/data/xinyi/image2reg/data_new/experiments/jump_compound/images/preprocessing/full_pipeline/20241025_161036"



